version: "3.3"

services:

{{#apiGW}}
  api:
    build:
      context: .
    image: {{projectName}}
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
{{#hasDepends}}
    depends_on:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - rabbitmq
{{/if_eq}}
{{#if_eq transporter "AMQP10"}}
      - activemq
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal
{{/apiGW}}

  greeter:
    build:
      context: .
    image: {{projectName}}
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
{{#hasDepends}}
    depends_on:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - rabbitmq
{{/if_eq}}
{{#if_eq transporter "AMQP10"}}
      - activemq
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
    networks:
      - internal
{{#dbService}}

  products:
    build:
      context: .
    image: {{projectName}}
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - rabbitmq
{{/if_eq}}
{{#if_eq transporter "AMQP10"}}
      - activemq
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal
{{/dbService}}
{{#if_eq transporter "NATS"}}

  nats:
    image: nats:2
    networks:
      - internal
{{/if_eq}}
{{#redis}}

  redis:
    image: redis:alpine
    networks:
      - internal
{{/redis}}
{{#if_eq transporter "MQTT"}}

  mqtt:
    image: ncarlier/mqtt
    networks:
      - internal
{{/if_eq}}
{{#if_eq transporter "AMQP"}}

  rabbitmq:
    image: rabbitmq:3
    networks:
      - internal
{{/if_eq}}
{{#if_eq transporter "AMQP10"}}

  activemq:
    image: rmohr/activemq
    networks:
      - internal
{{/if_eq}}
{{#if_eq transporter "STAN"}}

  stan:
    image: nats-streaming
    networks:
      - internal
{{/if_eq}}
{{#if_eq transporter "Kafka"}}

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - internal

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - internal
{{/if_eq}}

{{#apiGW}}
  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
{{/apiGW}}

networks:
  internal:

volumes:
  data:
