name: Generate a demo project

# on: [push, pull_request]
on: []

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install dependencies
      run: npm i
    - name: Generate project
      run: node_modules/.bin/moleculer init --answers test/demo/answers.json --no-install . project-demo

    - name: Initialize Git repo
      run: git init
      working-directory: ./project-demo

    - name: Set remote
      run: git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/moleculerjs/typescript-project-demo.git
      working-directory: ./project-demo

    - name: Add files
      run: git add --all
      working-directory: ./project-demo

    - name: Configure Git user
      run: git config --global user.email "hello@moleculer.services" && git config --global user.name "Moleculer"
      working-directory: ./project-demo

    - name: Commit
      run: git commit -m "Generated files"
      working-directory: ./project-demo
    
    - name: Git push
      run: git push --force origin master
      working-directory: ./project-demo
